#!/usr/bin/env python3
"""
Script to test Gmail integration.

This script uses the Gmail API to send a test email using
the tokens generated by get_token.py.
"""

import os
import base64
from email.mime.text import MIMEText
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

def main():
    """Send a test email using Gmail API."""
    print("Gmail API Test Script")
    
    # Check if token.json exists
    if not os.path.exists("token.json"):
        print("Error: token.json not found.")
        print("Please run get_token.py first to generate OAuth tokens.")
        return
    
    # Load credentials from token.json
    try:
        print("Loading credentials from token.json...")
        creds = Credentials.from_authorized_user_file("token.json")
    except Exception as e:
        print(f"Error loading credentials: {e}")
        return
    
    # Create Gmail API service
    try:
        print("Creating Gmail API service...")
        service = build("gmail", "v1", credentials=creds)
    except Exception as e:
        print(f"Error creating Gmail service: {e}")
        return
    
    # Get user's email address
    try:
        print("Getting user profile...")
        profile = service.users().getProfile(userId="me").execute()
        sender_email = profile["emailAddress"]
        print(f"Sender email: {sender_email}")
    except Exception as e:
        print(f"Error getting user profile: {e}")
        return
    
    # Get recipient email
    recipient = input("Enter recipient email address: ")
    
    # Create email content
    subject = "Test Email from AuditCue Integration"
    body = "This is a test email sent using the Gmail API from the AuditCue integration service."
    
    # Create message
    message = MIMEText(body)
    message["to"] = recipient
    message["from"] = sender_email
    message["subject"] = subject
    
    # Encode message
    raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode()
    
    # Send email
    try:
        print(f"Sending test email to {recipient}...")
        message = service.users().messages().send(
            userId="me", 
            body={"raw": raw_message}
        ).execute()
        print(f"Email sent successfully! Message ID: {message['id']}")
    except Exception as e:
        print(f"Error sending email: {e}")
        return
    
    print("Test completed successfully.")

if __name__ == "__main__":
    main()